[package]
name = "gex"
version = "0.1.0"
edition = "2021"
categories = ["command-line-utilities", "development-tools"]
description = "Git workflow improvement CLI tool inspired by Magit"
keywords = ["cli", "git", "workflow"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/Piturnah/gex"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.24.0"
nom = "7.1.1"
