[package]
name = "gex"
version = "0.4.1-dev"
edition = "2021"
categories = ["command-line-utilities", "development-tools"]
description = "Git workflow improvement CLI tool inspired by Magit"
keywords = ["cli", "git", "workflow"]
exclude = [".github/", ".gitignore", "shell.nix"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/Piturnah/gex"

[profile.release]
strip = true

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.3.11", features = ["cargo"] }
crossterm = "0.26.0"
git2 = { version = "0.17.1", default-features = false }
itertools = "0.11.0"
nom = "7.1.1"
paste = "1.0.12"

#       Tokee
#      (Gecko gekko)                _____________
#                            __,---'::.-  -::_ _ `-----.___      ______
#                        _,-'::_  ::-  -  -. _   ::-::_   .`--,'   :: .:`-._
#                     ,-'_ ::   _  ::_ .:   :: - _ .:   ::- _/ ::   ,-. ::. `-._
#                 _,-'   ::-  ::        ::-  _ ::  -  ::     |  .: ((|))      ::`.
#         ___,---'   ::    ::    ;::   ::     :.- _ ::._  :: \ :    `_____::..--'
#     ,-""  ::  ::.   ,------.  (.  ::  \  ::  ::  ,-- :. _  :`. ::  \       `-._
#   ,'     ::   '   _._.:_  :.)___,-------------._(.:: ____`-._ `._ ::`--...___; ;
#  ;:::. ,--'--"""""      /  /                     \. |     ``-----`''`---------'
# ;  `::;              _ /.:/_,                    _\.:\_,
# |    ;  jrei       ='-//\\--"                  ='-//\\--"
# `   .|               ''  ``                      ''  ``
#  \::'\
#   \   \
#    `..:`.
#      `.  `--.____
#        `-:______ `-._
#                 `---'`
#
#                   (gecko art found at https://ascii.co.uk/art)
