# Used https://github.com/taiki-e/cargo-hack/blob/202e6e59d491c9202ce148c9ef423853267226db/.github/workflows/release.yml#L47-L84 as example
name: CD

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  bins:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build and upload Rust binary to GitHub Releases
        uses: taiki-e/upload-rust-binary-action@v1.11.1
        with:
          bin: gex
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          CARGO_PROFILE_RELEASE_LTO: true
          CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1

